name: Rust-ci


on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFile('**/Cargo.lock') }}
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose

